FROM node:20-buster-slim

WORKDIR /app

COPY package.json pnpm-lock.yaml ./
COPY . .
RUN npm i -g pnpm
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"

RUN pnpm install
RUN pnpm install -g nodemon

EXPOSE 4001
CMD ["pnpm", "run", "dev"]
